// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6eJBtDFzFOTd5nFke8VzIxOfYWFwfFk',
    appId: '1:676300981362:web:67c7ffb1f9ad61365c2eeb',
    messagingSenderId: '676300981362',
    projectId: 'varatalapp-001',
    authDomain: 'varatalapp-001.firebaseapp.com',
    storageBucket: 'varatalapp-001.firebasestorage.app',
    measurementId: 'G-EN4EEDDFEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwh5J2R4bl1cx20PG6HDztjdjZ-F9T7f8',
    appId: '1:676300981362:android:072e27f2507e59185c2eeb',
    messagingSenderId: '676300981362',
    projectId: 'varatalapp-001',
    storageBucket: 'varatalapp-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgWwJNQ25twUOItexJU3oxVwMLEhlicRw',
    appId: '1:676300981362:ios:cfa7e3d8658026035c2eeb',
    messagingSenderId: '676300981362',
    projectId: 'varatalapp-001',
    storageBucket: 'varatalapp-001.firebasestorage.app',
    iosBundleId: 'com.example.varatalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgWwJNQ25twUOItexJU3oxVwMLEhlicRw',
    appId: '1:676300981362:ios:cfa7e3d8658026035c2eeb',
    messagingSenderId: '676300981362',
    projectId: 'varatalapp-001',
    storageBucket: 'varatalapp-001.firebasestorage.app',
    iosBundleId: 'com.example.varatalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW6eJBtDFzFOTd5nFke8VzIxOfYWFwfFk',
    appId: '1:676300981362:web:e78cacac659e41bc5c2eeb',
    messagingSenderId: '676300981362',
    projectId: 'varatalapp-001',
    authDomain: 'varatalapp-001.firebaseapp.com',
    storageBucket: 'varatalapp-001.firebasestorage.app',
    measurementId: 'G-FWM22LX5ET',
  );
}
